version: '3.6'

services:

  tests-pg:
    image: postgres:$POSTGRES_VERSION
    environment:
      - 'POSTGRES_DB=$POSTGRES_DB'
      - 'POSTGRES_USER=$POSTGRES_USER'
      - 'POSTGRES_PASSWORD=$POSTGRES_PASSWORD'
    volumes:
      - ./docker/pg/create-users.sql:/docker-entrypoint-initdb.d/create-users.sql
    ports:
      - $POSTGRES_LOCAL_PORT:5432


  tests-config:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-image
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: .env
    environment:
      - 'SOLVER_POSTGRES_URL=postgresql+psycopg://swpt_solver:swpt_solver@tests-pg:5432/${POSTGRES_DB}'
      - 'WORKER_POSTGRES_URL=postgresql+psycopg://swpt_worker:swpt_worker@tests-pg:5432/${POSTGRES_DB}'
      - 'PYTHONDONTWRITEBYTECODE=1'
    command: configure
    depends_on:
      - tests-pg


  tests-web:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-image
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: .env
    environment:
      - 'WEBSERVER_PORT=8080'
      - 'SOLVER_POSTGRES_URL=postgresql+psycopg://swpt_solver:swpt_solver@tests-pg:5432/${POSTGRES_DB}'
      - 'PYTHONDONTWRITEBYTECODE=1'
    ports:
      - $WEBSERVER_PORT:8080
    command: develop-run-flask
    depends_on:
      - tests-pg
