"""empty message

Revision ID: 0693d4e041bb
Revises: 67096fdced2c
Create Date: 2026-01-30 21:08:05.517428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0693d4e041bb'
down_revision = '67096fdced2c'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('most_bought_currency',
    sa.Column('debtor_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('buyers_average_count', sa.REAL(), nullable=False),
    sa.Column('debtor_info_locator', sa.String(), nullable=False),
    sa.CheckConstraint('buyers_average_count >= 0.0'),
    sa.PrimaryKeyConstraint('debtor_id'),
    comment='Represents the fact that currently, according to the collected trade statistics, a given currency is among the most bought currencies.'
    )
    # ### end Alembic commands ###


def downgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('most_bought_currency')
    # ### end Alembic commands ###

