"""empty message

Revision ID: 1152afda898d
Revises: 6a5138f3e30f
Create Date: 2025-11-21 15:21:04.043432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1152afda898d'
down_revision = '6a5138f3e30f'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_lock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_locked_amount', sa.BigInteger(), nullable=False, comment='An upper limit for the actual locked amount.'))
        batch_op.create_check_constraint(None, 'max_locked_amount >= 0')

    with op.batch_alter_table('needed_worker_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blocked_amount', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('blocked_amount_ts', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.create_check_constraint(None, 'blocked_amount >= 0')
        batch_op.create_check_constraint(None, 'blocked_amount IS NULL AND blocked_amount_ts IS NULL OR blocked_amount IS NOT NULL AND blocked_amount_ts IS NOT NULL')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('needed_worker_account', schema=None) as batch_op:
        batch_op.drop_column('blocked_amount_ts')
        batch_op.drop_column('blocked_amount')

    with op.batch_alter_table('account_lock', schema=None) as batch_op:
        batch_op.drop_column('max_locked_amount')

    # ### end Alembic commands ###


def upgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

