"""empty message

Revision ID: 27f233d389d5
Revises: 7bb7287d66b9
Create Date: 2025-11-25 17:08:24.534615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27f233d389d5'
down_revision = '7bb7287d66b9'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activate_collector_signal')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activate_collector_signal',
    sa.Column('signal_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('debtor_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('creditor_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('signal_id', name=op.f('activate_collector_signal_pkey'))
    )
    # ### end Alembic commands ###


def upgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

