"""empty message

Revision ID: 2c35913928c1
Revises: 74827f597d1b
Create Date: 2025-11-09 18:12:20.861322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c35913928c1'
down_revision = '74827f597d1b'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surplus_amount', sa.BigInteger(), nullable=False, comment='The calculated surplus on this account. The surplus can be spent on behalf of the owner of the creditors agent node.'))
        batch_op.add_column(sa.Column('surplus_ts', sa.TIMESTAMP(timezone=True), nullable=False, comment='The moment when the surplus was observed. This is needed so that, for the current moment, we can calculate the maximum possible demurrage that surplus may have suffered.'))
        batch_op.add_column(sa.Column('surplus_spent_amount', sa.BigInteger(), nullable=False, comment='The surplus amount which already has been spent on behalf of the owner of the creditors agent node.'))
        batch_op.add_column(sa.Column('surplus_last_transfer_number', sa.BigInteger(), nullable=False, comment='This number must be incremented each time when `surplus_ts` change, or a trade has been made on behalf of the owner of the creditors agent node. This is necessary in order to avoid double-spending and double-buying.'))

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_account', schema=None) as batch_op:
        batch_op.drop_column('surplus_last_transfer_number')
        batch_op.drop_column('surplus_spent_amount')
        batch_op.drop_column('surplus_ts')
        batch_op.drop_column('surplus_amount')

    # ### end Alembic commands ###


def upgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

