"""empty message

Revision ID: 3cfbf4c7d0b3
Revises: 1152afda898d
Create Date: 2025-11-23 12:44:59.512884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3cfbf4c7d0b3'
down_revision = '1152afda898d'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usable_collector',
    sa.Column('debtor_id', sa.BigInteger(), nullable=False),
    sa.Column('collector_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('disabled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("account_id != ''"),
    sa.PrimaryKeyConstraint('debtor_id', 'collector_id'),
    comment='Represents an existing Swaptacular account which can be used to collect and dispatch transfers. Each "Worker" servers will maintain its own copy of this table (that is: no rows-sharding) by periodically copying the relevant records from the solver\'s "collector_account" table. "Worker" servers will use this local copy so as to avoid querying the central database too often.'
    )
    with op.batch_alter_table('usable_collector', schema=None) as batch_op:
        batch_op.create_index('idx_usable_collector_collector_id', ['collector_id', 'debtor_id'], unique=True)

    with op.batch_alter_table('useful_collector', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_useful_collector_collector_id'))

    op.drop_table('useful_collector')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('useful_collector',
    sa.Column('debtor_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('collector_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('disabled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("account_id::text <> ''::text", name=op.f('useful_collector_account_id_check')),
    sa.PrimaryKeyConstraint('debtor_id', 'collector_id', name=op.f('useful_collector_pkey')),
    comment='Represents an existing Swaptacular account which can be used to collect and dispatch transfers. Each "Worker" servers will maintain its own copy of this table (that is: no rows-sharding) by periodically copying the relevant records from the solver\'s "collector_account" table. "Worker" servers will use this local copy so as to avoid querying the central database too often.'
    )
    with op.batch_alter_table('useful_collector', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_useful_collector_collector_id'), ['collector_id', 'debtor_id'], unique=True)

    with op.batch_alter_table('usable_collector', schema=None) as batch_op:
        batch_op.drop_index('idx_usable_collector_collector_id')

    op.drop_table('usable_collector')
    # ### end Alembic commands ###


def upgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

