"""empty message

Revision ID: 67096fdced2c
Revises: 13c9124c25ec
Create Date: 2026-01-23 13:22:09.451264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67096fdced2c'
down_revision = '13c9124c25ec'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_lock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_collector', sa.BOOLEAN(), nullable=False))
        batch_op.create_index('idx_lock_account_unreleased_collector_locks', ['creditor_id', 'debtor_id'], unique=True, postgresql_where=sa.text('is_collector = true AND released_at IS NULL'))

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_lock', schema=None) as batch_op:
        batch_op.drop_index('idx_lock_account_unreleased_collector_locks', postgresql_where=sa.text('is_collector = true AND released_at IS NULL'))
        batch_op.drop_column('is_collector')

    # ### end Alembic commands ###


def upgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

