"""empty message

Revision ID: 74827f597d1b
Revises: 7e890df567aa
Create Date: 2025-11-07 12:09:39.367335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74827f597d1b'
down_revision = '7e890df567aa'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overloaded_currency',
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.Column('debtor_id', sa.BigInteger(), nullable=False),
    sa.Column('collectors_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('collectors_count > 0'),
    sa.PrimaryKeyConstraint('turn_id', 'debtor_id'),
    comment='Represents the fact that during the given trading turn, the number of active collector accounts with the given currency have been too small to handle all the transfers.'
    )
    # ### end Alembic commands ###


def downgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('overloaded_currency')
    # ### end Alembic commands ###

