"""empty message

Revision ID: 76921c63a0b4
Revises: cdcaf7b61de5
Create Date: 2025-11-17 19:35:34.889966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76921c63a0b4'
down_revision = 'cdcaf7b61de5'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('needed_worker_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collection_disabled_since', sa.TIMESTAMP(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('needed_worker_account', schema=None) as batch_op:
        batch_op.drop_column('collection_disabled_since')

    # ### end Alembic commands ###


def upgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

