"""empty message

Revision ID: 7bb7287d66b9
Revises: 7f5df19fb145
Create Date: 2025-11-25 15:43:24.647661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb7287d66b9'
down_revision = '7f5df19fb145'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collector_status_change',
    sa.Column('collector_id', sa.BigInteger(), nullable=False),
    sa.Column('change_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('debtor_id', sa.BigInteger(), nullable=False),
    sa.Column('from_status', sa.SmallInteger(), nullable=False),
    sa.Column('to_status', sa.SmallInteger(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.CheckConstraint('from_status = 0 AND to_status = 1 AND account_id IS NULL OR from_status = 1 AND to_status = 2 AND account_id IS NOT NULL OR from_status = 3 AND to_status = 2 AND account_id IS NULL OR from_status = 3 AND to_status = 1 AND account_id IS NULL'),
    sa.PrimaryKeyConstraint('collector_id', 'change_id'),
    comment='Represents a pending change in the status of a collector account on the solver server.'
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collector_status_change')
    # ### end Alembic commands ###


def upgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

