"""empty message

Revision ID: 7e890df567aa
Revises: 88cd664f51a3
Create Date: 2025-09-03 14:58:31.988079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e890df567aa'
down_revision = '88cd664f51a3'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delayed_account_transfer',
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creditor_id', sa.BigInteger(), nullable=False),
    sa.Column('debtor_id', sa.BigInteger(), nullable=False),
    sa.Column('creation_date', sa.DATE(), nullable=False),
    sa.Column('transfer_number', sa.BigInteger(), nullable=False),
    sa.Column('coordinator_type', sa.String(length=30), nullable=False),
    sa.Column('committed_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('acquired_amount', sa.BigInteger(), nullable=False),
    sa.Column('transfer_note_format', sa.TEXT(), nullable=False),
    sa.Column('transfer_note', sa.TEXT(), nullable=False),
    sa.Column('principal', sa.BigInteger(), nullable=False),
    sa.Column('previous_transfer_number', sa.BigInteger(), nullable=False),
    sa.Column('sender', sa.String(length=100), nullable=False),
    sa.Column('recipient', sa.String(length=100), nullable=False),
    sa.Column('ts', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('turn_id', 'message_id'),
    comment='Represents an `AccountTransfer` SMP message which has been triggered by the actions of another worker, and has been received by this worker, before it is ready to process it. Such messages will be saved in this table, in order to be "replayed" once this worker is ready to process them.'
    )
    op.create_table('replayed_account_transfer_signal',
    sa.Column('signal_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creditor_id', sa.BigInteger(), nullable=False),
    sa.Column('debtor_id', sa.BigInteger(), nullable=False),
    sa.Column('creation_date', sa.DATE(), nullable=False),
    sa.Column('transfer_number', sa.BigInteger(), nullable=False),
    sa.Column('coordinator_type', sa.String(length=30), nullable=False),
    sa.Column('committed_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('acquired_amount', sa.BigInteger(), nullable=False),
    sa.Column('transfer_note_format', sa.TEXT(), nullable=False),
    sa.Column('transfer_note', sa.TEXT(), nullable=False),
    sa.Column('principal', sa.BigInteger(), nullable=False),
    sa.Column('previous_transfer_number', sa.BigInteger(), nullable=False),
    sa.Column('sender', sa.String(length=100), nullable=False),
    sa.Column('recipient', sa.String(length=100), nullable=False),
    sa.Column('ts', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('signal_id')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replayed_account_transfer_signal')
    op.drop_table('delayed_account_transfer')
    # ### end Alembic commands ###


def upgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

