"""empty message

Revision ID: a19e156bb8fd
Revises: b2aa9366dfda
Create Date: 2025-11-12 14:41:12.574425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a19e156bb8fd'
down_revision = 'b2aa9366dfda'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hoarded_currency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peg_debtor_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('peg_exchange_rate', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###


def downgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hoarded_currency', schema=None) as batch_op:
        batch_op.drop_column('peg_exchange_rate')
        batch_op.drop_column('peg_debtor_id')

    # ### end Alembic commands ###

