"""empty message

Revision ID: b2aa9366dfda
Revises: 2c35913928c1
Create Date: 2025-11-11 16:33:29.214848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2aa9366dfda'
down_revision = '2c35913928c1'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hoarded_currency',
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.Column('debtor_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('turn_id', 'debtor_id'),
    comment='Represents the fact that during the given trading turn, the owner of the creditors agent node wants to buy (hoard) the given currency.'
    )
    # ### end Alembic commands ###


def downgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hoarded_currency')
    # ### end Alembic commands ###

