"""empty message

Revision ID: cdcaf7b61de5
Revises: 7e890df567aa
Create Date: 2025-11-14 19:08:19.769129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdcaf7b61de5'
down_revision = '7e890df567aa'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surplus_amount', sa.BigInteger(), nullable=False, comment='The calculated surplus on this account. The surplus can be spent on behalf of the owner of the creditors agent node.'))
        batch_op.add_column(sa.Column('surplus_ts', sa.TIMESTAMP(timezone=True), nullable=False, comment='The moment when the surplus was observed. This is needed so that, for the current moment, we can calculate the maximum possible demurrage that surplus may have suffered.'))
        batch_op.add_column(sa.Column('surplus_spent_amount', sa.BigInteger(), nullable=False, comment='The surplus amount which already has been spent on behalf of the owner of the creditors agent node.'))
        batch_op.add_column(sa.Column('surplus_last_transfer_number', sa.BigInteger(), nullable=False, comment='This number must be incremented each time when `surplus_ts` change, or a trade has been made on behalf of the owner of the creditors agent node. This is necessary in order to avoid double-spending and double-buying.'))

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_account', schema=None) as batch_op:
        batch_op.drop_column('surplus_last_transfer_number')
        batch_op.drop_column('surplus_spent_amount')
        batch_op.drop_column('surplus_ts')
        batch_op.drop_column('surplus_amount')

    # ### end Alembic commands ###


def upgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hoarded_currency',
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.Column('debtor_id', sa.BigInteger(), nullable=False),
    sa.Column('peg_debtor_id', sa.BigInteger(), nullable=True),
    sa.Column('peg_exchange_rate', sa.FLOAT(), nullable=True),
    sa.CheckConstraint('peg_debtor_id IS NULL AND peg_exchange_rate IS NULL OR peg_debtor_id IS NOT NULL AND peg_exchange_rate IS NOT NULL'),
    sa.CheckConstraint('peg_exchange_rate >= 0.0'),
    sa.PrimaryKeyConstraint('turn_id', 'debtor_id'),
    comment='Represents the fact that during the given trading turn, the owner of the creditors agent node wants to buy (hoard) the given currency.'
    )
    op.create_table('overloaded_currency',
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.Column('debtor_id', sa.BigInteger(), nullable=False),
    sa.Column('collectors_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('collectors_count > 0'),
    sa.PrimaryKeyConstraint('turn_id', 'debtor_id'),
    comment='Represents the fact that during the given trading turn, the number of active collector accounts with the given currency have been too small to handle all the transfers.'
    )
    # ### end Alembic commands ###


def downgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('overloaded_currency')
    op.drop_table('hoarded_currency')
    # ### end Alembic commands ###

