"""empty message

Revision ID: f1b53b53caa4
Revises: ebdeda5d0d24
Create Date: 2025-12-04 17:28:49.625285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1b53b53caa4'
down_revision = 'ebdeda5d0d24'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('needed_worker_account', schema=None) as batch_op:
        batch_op.alter_column('blocked_amount',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('blocked_amount_ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('needed_worker_account', schema=None) as batch_op:
        batch_op.alter_column('blocked_amount_ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('blocked_amount',
               existing_type=sa.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###


def upgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

